### ISSUE TITLE
(Startup) Program launch

### ISSUE THREAD

**Issue by kalw** [serras/SparkleShare#14]
Hi there,

After a succesful build and install process under windows 7 [link here](https://github.com/downloads/kalw/SparkleShare/SparkleShare.msi):
    - sparkleshare executable launch crash.
    - sparkleshare startup launch crash

I have to launch it every time manually with administrator privileges.

What can we do ? =)
## 

Regis A. Despres

**Comment by hbons** [comment]
@kalw there's now a .msi on my repo which should work without

**Comment by kalw** [comment]
yep it's functionnal =)

from now, do we have to swtich to your repository if we want to build the windows version ?

## 

Regis A. Despres

**Comment by hbons** [comment]
@kalw yep, all development is going on on my repo now :)

**Comment by kalw** [comment]
ok , cool.

## 

Regis A. Despres
