### ISSUE TITLE
Got it to compile, can't finish initial setup wizard

### ISSUE THREAD

**Issue by izzy84075** [serras/SparkleShare#6]
Managed to get it to compile, after reading through some of the other issues and pull requests, and built the installer. Now I can't click the "Next" button when it asks for my name and email address. Not sure what to do to help debug this, but I figured I'd let you know.

**Comment by snauth** [comment]
Same problem here (win7/64), manually editing config.xml and adding the ssh keys to the AppData/roaming/sparkleshare directory got me one step further, but I am still not able to add folders. I have another instance running on a Win xp/32 bit machine that works flawless (0.4.0-131-ga4496cb).

**Comment by izzy84075** [comment]
Sounds like it's either a Windows 7 thing, or a 64-bit thing... Don't have a win7/32 machine handy to see which, though.

**Comment by izzy84075** [comment]
Been poking through Windows/SparkleSetup.Designer.cs, and I don't think the Next button is attached to any code... The textboxes enable, disable it, but there's no Click() event attached to it... I'll have a pull request in a sec to fix it.

See https://github.com/serras/SparkleShare/pull/7 for the pull request. Probably a way to attach it to this, but I don't know how.

**Comment by izzy84075** [comment]
Fixed with https://github.com/serras/SparkleShare/commit/e1e97ef96628dd1152754bc544b7178dd4cfa8e5 .
