### ISSUE TITLE
Exception when syncing a file (the sparkleshare.msi)

### ISSUE THREAD

**Issue by Thirsty2** [serras/SparkleShare#8]
I decided the easiest way to get the sparkleshare.msi windows installer I just built onto my work computer was to copy it to the sparkleshare directory syncing with my gitolite repo.  I had tested a few small text files successfully, but when I copied the .msi file to the sparkleshare dir, it took a while (not unexpected, since it is a fairly large file.)  I right clicked on the toolbark icon and saw that it was still syncing.  Ok.  No problem.  But eventually I got the following exception, which I copied and pasted from the .Net Framework exception dialog box that popped up:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.Runtime.InteropServices.ExternalException: A generic error occurred in GDI+.
   at System.Drawing.Bitmap.GetHicon()
   at SparkleShare.SparkleStatusIcon.<CreateAnimation>b__e()
   at SparkleShare.ControlExtention.SafeInvoke(Control uiElement, Action updater, Boolean forceSynchronous)
   at SparkleShare.SparkleStatusIcon.<CreateAnimation>b__d(Object , EventArgs )
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5448 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

SparkleShare
    Assembly Version: 8.1.0.0
    Win32 Version: 8.1.0.167
##     CodeBase: file:///C:/Program%20Files%20(x86)/sparkleshare.org/SparkleShare/SparkleShare.exe

SparkleLib
    Assembly Version: 8.1.0.0
    Win32 Version: 8.1.0.167
##     CodeBase: file:///C:/Program%20Files%20(x86)/sparkleshare.org/SparkleShare/SparkleLib.DLL

CefSharp
    Assembly Version: 0.3.4006.34354
    Win32 Version: 
##     CodeBase: file:///C:/Program%20Files%20(x86)/sparkleshare.org/SparkleShare/CefSharp.DLL

msvcm90
    Assembly Version: 9.0.30729.6161
    Win32 Version: 9.00.30729.6161
##     CodeBase: file:///C:/Windows/WinSxS/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_50934f2ebcb7eb57/msvcm90.dll

System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5447 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

Gettext.Cs
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/sparkleshare.org/SparkleShare/Gettext.Cs.DLL

System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5446 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Core
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.5420 built by: Win7SP1
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by serras** [comment]
I've pushed some changes that should fix this problem. I'll keep this open a week more, in case any more error appear.
Thanks for reporting.
