### ISSUE TITLE
wrong Repo Path crashes programm

### ISSUE THREAD

**Issue by spisoft** [serras/SparkleShare#9]
after i found out how to set up an own git server in the right way: http://sparkleshare.org/set-up-a-host/ 
i noticed, that if the path on the git server is wrong the program crashes. 

When the server is wrong  the page where the parsed Server Path should be shown does not show this path (using german local) like it does with the linux edition.

maybe the help text for "on my own server" shold be user@domain name or user @ ip adress or there should be a third field for the user to helb newbies like me typing the right things...

last thing: the installer should provide a way to change the location of the sparkleshare folder. Win7 stores it to My Dokuments but maybe the user wants it to his profile path..

but at the moment i am happy to have a running sparklesahre, very good work thanks :-)
thank you

**Comment by serras** [comment]
Thanks for reporting. I've fixed the error message.
About the help text for "own server", this part depends on the main SparkleShare repo, so maybe you should open a request there.

**Comment by hbons** [comment]
I've added a little hint label below the server field on the mac and linux UIs. It would just be a matter of adding a label and hooking up a UI event.

**Comment by spisoft** [comment]
this shuold be enough to recognize how to type the right path
